apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: mcdomain
  name: mcdomain
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: mcdomain-manager-role
  labels:
    app: mcdomain
rules:
- apiGroups:
  - fun.xcc
  resources:
  - domainowners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fun.xcc
  resources:
  - domainowners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcdomain-manager-rolebinding
  labels:
    app: mcdomain
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcdomain-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: mcdomain

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcdomain
  namespace: mcdomain
  labels:
    app: mcdomain
spec:
  selector:
    matchLabels:
      app: mcdomain
  replicas: 1
  template:
    metadata:
      labels:
        app: mcdomain
    spec:
      containers:
      - name: manager
        image: ko://github.com/rosenhouse/mcdomain
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
